-- MySQL Script generated by MySQL Workbench
-- Tue Dec  8 20:54:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test_temporal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_temporal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_temporal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `test_temporal` ;

-- -----------------------------------------------------
-- Table `test_temporal`.`dalu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`dalu` (
  `ctr` CHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nom` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `esp` INT(10) NOT NULL,
  `sem` TINYINT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`ctr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`dcat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`dcat` (
  `cve` INT(3) UNSIGNED NOT NULL,
  `dep` INT(3) NOT NULL,
  `nom` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`cve`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`ddep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`ddep` (
  `cve` INT(3) UNSIGNED NOT NULL,
  `nom` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nco` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`cve`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`desp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`desp` (
  `cve` INT(3) UNSIGNED NOT NULL,
  `nom` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nco` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`cve`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`dgau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`dgau` (
  `gpo` CHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `cat` INT(3) NOT NULL,
  `mat` CHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  UNIQUE INDEX `gpo_UNIQUE` USING BTREE (`gpo`, `mat`),
  INDEX `FK_dgau_grupo_idx` (`gpo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`dlis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`dlis` (
  `ctr` CHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `gpo` CHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `mat` CHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`dret`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`dret` (
  `cve` CHAR(4) NOT NULL,
  `nom` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nco` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`cve`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `test_temporal`.`grup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_temporal`.`grup` (
  `cve` CHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nombre` CHAR(5) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`cve`),
  UNIQUE INDEX `nombre_cve_UNIQUE` (`cve` ASC, `nombre` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
